### ISSUE TITLE
How to change datepicker format?

### ISSUE THREAD

**Issue by janmhamburg** [creativetimofficial/ct-white-dashboard-pro-laravel#1]
I'm using the datepicker in White Dashboard PRO Laravel. As seen on form_extended.blade. I used class="form-control datepicker" with:
<script>
    $(document).ready(function() {´
      whiteDashboard.initDateTimePicker();
    });
  </script>
It works. But how can I change the date format from 'MM/DD/YYYY' to (german) 'DD.MM.YYYY'? Thank you in advance for your help!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi @janmhamburg,

Thank you for using Creative-Tim products!

In order to solve your problem you have to replace this code:

`whiteDashboard.initDateTimePicker();`

with this code:

`var $datepicker = $('.datepicker');
      $datepicker.datetimepicker({
        format: 'MM.DD.YYYY',
      });`

Best,

UPDIVISION

**Comment by teamupdivision** [comment]
Hi @janmhamburg,

Hope you solved the problem. I will go ahead and close this ticket.

Best,

UPDIVISION

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
